### ISSUE TITLE
facet doesn't work with ods-widgets.min.js but does with ods-widgets.js

### ISSUE THREAD

**Issue by yaca29** [opendatasoft/ods-widgets#47] opened 2015-02-23 20:33 UTC
Hi,

With this context

                            <ods-dataset-context context="etab" etab-domain="mesr" etab-dataset="fr-esr-principaux-etablissements-enseignement-superieur" etab-parameters="{'sort': 'aca_nom', 'refine.identifiant_programme_lolf_chef_de_file': '150'}">

this code doesn't diplay the facets if i use ods-widgets.min.js but works with ods-widget.js :

<ods-facets context="etab">
    <h3>Filtrer par académie</h3>
    <ods-facet name="aca_nom" visible-items="33">{{category.name}}</ods-facet>
</ods-facets>

Any solutions ?

Kindly

Yann

ps : log is here :
 Error: [$injector:unpr] Unknown provider: eProvider <- e <- odsFacetsDirective
http://errors.angularjs.org/1.2.22/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20odsFacetsDirective
    at angular.js:78
    at angular.js:3792
    at Object.getService [as get] (angular.js:3920)
    at angular.js:3797
    at getService (angular.js:3920)
    at Object.invoke (angular.js:3947)
    at angular.js:5671
    at forEach (angular.js:325)
    at Object.<anonymous> (angular.js:5669)
    at Object.invoke (angular.js:3956)
angular.js:10046 Error: [$injector:unpr] Unknown provider: eProvider <- e <- odsFacetCategoryDirective
http://errors.angularjs.org/1.2.22/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20odsFacetCategoryDirective
    at angular.js:78
    at angular.js:3792
    at Object.getService [as get] (angular.js:3920)
    at angular.js:3797
    at getService (angular.js:3920)
    at Object.invoke (angular.js:3947)
    at angular.js:5671
    at forEach (angular.js:325)
    at Object.<anonymous> (angular.js:5669)
    at Object.invoke (angular.js:3956)
angular.js:10046 Error: [$compile:ctreq] Controller 'odsFacets', required by directive 'odsFacet', can't be found!
http://errors.angularjs.org/1.2.22/$compile/ctreq?p0=odsFacets&p1=odsFacet
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.js:78:12
    at getControllers (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.js:6524:19)
    at nodeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.js:6693:35)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.js:6086:13)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.js:6089:13)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.js:6089:13)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.js:6089:13)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.js:6089:13)
    at compositeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.js:6089:13)
    at nodeLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.22/angular.js:6686:24) <div class="odswidget odswidget-facet ng-isolate-scope" name="aca_nom" visible-items="33">

**Comment by richterb** [comment] 2015-02-23 20:36
Ah yes, ugly bug on our side. The minification breaks the "magical dependency injection" from Angular, and I neglected to use the right syntax to prevent this. I'll check that it doesn't happen in other places as well, and push a fix.

**Comment by yaca29** [comment] 2015-02-23 20:48
thanks

**Comment by richterb** [comment] 2015-02-23 20:55
It should be fixed, you can try the last version of the minified distribution here: https://raw.githubusercontent.com/opendatasoft/ods-widgets/gh-pages/dist/ods-widgets.min.js

**Comment by yaca29** [comment] 2015-02-23 23:09
![capture d ecran 2015-02-23 a 23 59 57](https://cloud.githubusercontent.com/assets/6418278/6339659/69227d6a-bbb8-11e4-8b5d-4686388dd6a8.png)
hi,
yes, facets appears now, but there is now a problem in icons on map, like in that picture, with both files : 
https://raw.githubusercontent.com/opendatasoft/ods-widgets/gh-pages/dist/ods-widgets.min.js
https://raw.githubusercontent.com/opendatasoft/ods-widgets/gh-pages/dist/ods-widgets.js

**Comment by richterb** [comment] 2015-02-23 23:15
Looks like a missing CSS, I'll have a look first thing in the morning

**Comment by richterb** [comment] 2015-02-24 08:06
I can't reproduce it, and the only CSS you miss are the new ones. If you took the new ods-widgets.min.js but didn't take the last release from friday, it is the cause.  So you'd need to:
- take the last version at https://github.com/opendatasoft/ods-widgets/releases/tag/0.1.5
- add the new ods-widgets.min.js from yesterday, as I didn't patch it in a new release yet

**Comment by yaca29** [comment] 2015-02-24 09:38
yes you're right, just forgot the new css. It's work now thanks

**Comment by richterb** [comment] 2015-02-24 09:39
No problem :)

**Closed** 2015-02-24 09:39 UTC
